# 準備

## sys.pathの設定

以下では，Googleドライブのマイドライブ直下にDNN_codeフォルダを置くことを仮定しています．必要に応じて，パスを変更してください．

In [23]:
import sys
sys.path.append('./')

In [24]:
sys.path.append('../common')

In [25]:
!ls ../

README.md  data     lesson_1  productionChallenges  requirements.txt
common	   example  lesson_2  requirements.in


In [26]:
!ls ../common

__pycache__  functions.py  layers.py  optimizer.py  trainer.py


# importと関数定義

In [34]:
import numpy as np
#from common import functions
import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    #print("shape: " + str(x.shape))
    print("")


# 順伝播（単層・単ユニット）

In [39]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = 0.5

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[0 4]

*** バイアス ***
4.432172846531083

*** 入力 ***
[2 3]

*** 総入力 ***
16.43217284653108

*** 中間層出力 ***
16.43217284653108



# 順伝播（単層・複数ユニット）


In [40]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[3 3 2]
 [1 2 0]
 [2 0 2]
 [3 0 2]]

*** バイアス ***
[0.1 0.2 0.3]

*** 入力 ***
[ 1.  5.  2. -1.]

*** 総入力 ***
[ 9.1 13.2  4.3]

*** 中間層出力 ***
[0.99988835 0.99999815 0.98661308]



# 順伝播（3層・複数ユニット）

In [46]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W1']=np.random.rand(2,3)
    print(network["W1"].shape)
    
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W2']=np.random.rand(3,2)
    print(network["W2"].shape)
    
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['W3']=np.random.rand(2,2)
    print(network["W3"].shape)
    print("")
    
    network['b1'] = np.random.rand(3) #np.array([0.1, 0.2, 0.3])
    network['b2'] = np.random.rand(2) #np.array([0.1, 0.2])
    network['b3'] = np.random.rand(2) #np.array([1, 2])

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2.]

##### ネットワークの初期化 #####
(2, 3)
(3, 2)
(2, 2)

*** 重み1 ***
[[0.45381228 0.89622265 0.7769808 ]
 [0.19368377 0.78981461 0.14222265]]

*** 重み2 ***
[[0.11219197 0.32535455]
 [0.56239623 0.70442567]
 [0.33283144 0.78734784]]

*** 重み3 ***
[[0.73954205 0.80469194]
 [0.91037625 0.81202272]]

*** バイアス1 ***
[0.91003964 0.27645843 0.27521534]

*** バイアス2 ***
[0.27152716 0.03472368]

*** バイアス3 ***
[0.81890673 0.38189273]

##### 順伝播開始 #####
*** 総入力1 ***
[1.75121947 2.7523103  1.33664145]

*** 中間層出力1 ***
[1.75121947 2.7523103  1.33664145]

*** 総入力2 ***
[2.46076517 3.59569067]

*** 出力1 ***
[1.75121947 2.7523103  1.33664145]

出力合計: 5.8401712211902375


# 多クラス分類（2-3-4ネットワーク）

In [48]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5, 0.1, 0.1],
        [0.2, 0.4, 0.6, 0.1, 0.1],
        [0.2, 0.4, 0.6, 0.1, 0.1]
    ])
    network['W2'] = np.array([
        [0.1, 0.4, 0.7, 1.0],
        [0.2, 0.5, 0.8, 1.1],
        [0.3, 0.6, 0.9, 1.2],
        [0.3, 0.6, 0.9, 1.2],
        [0.3, 0.6, 0.9, 1.2]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1 0.3 0.5 0.1 0.1]
 [0.2 0.4 0.6 0.1 0.1]
 [0.2 0.4 0.6 0.1 0.1]]

*** 重み2 ***
[[0.1 0.4 0.7 1. ]
 [0.2 0.5 0.8 1.1]
 [0.3 0.6 0.9 1.2]
 [0.3 0.6 0.9 1.2]
 [0.3 0.6 0.9 1.2]]

*** バイアス1 ***
[0.1 0.2 0.3 0.4 0.5]

*** バイアス2 ***
[0.1 0.2 0.3 0.4]

##### 順伝播開始 #####
*** 総入力1 ***
[1.2 2.5 3.8 1.  1.1]

*** 中間層出力1 ***
[1.2 2.5 3.8 1.  1.1]

*** 総入力2 ***
[ 2.49  5.47  8.45 11.43]

*** 出力1 ***
[1.24385922e-04 2.44888723e-03 4.82132428e-02 9.49213484e-01]

出力合計: 1.0

##### 結果表示 #####
*** 出力 ***
[1.24385922e-04 2.44888723e-03 4.82132428e-02 9.49213484e-01]

*** 訓練データ ***
[0 0 0 1]

*** 誤差 ***
0.05212144347300637



# 回帰（2-3-2ネットワーク）

In [51]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.random.rand(3,5)
    network['W2'] = np.random.rand(5,4)
    network['b1'] = np.random.rand(5) #np.array([0.1, 0.2, 0.3])
    network['b2'] = np.random.rand(4) #np.array([0.1, 0.2])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.14196473 0.94069358 0.95872147 0.60156737 0.02967932]
 [0.20781821 0.00172539 0.41754243 0.13687174 0.40882726]
 [0.79137213 0.83533707 0.84632806 0.93363331 0.59195463]]

*** 重み2 ***
[[0.4783427  0.07815895 0.4809112  0.00940366]
 [0.66821675 0.70834908 0.66648685 0.61397271]
 [0.11968378 0.59210121 0.70814368 0.21122124]
 [0.04162011 0.34560523 0.33697355 0.29197739]
 [0.0344727  0.53389454 0.21455475 0.02742013]]

*** バイアス1 ***
[0.5378205  0.38972146 0.51202185 0.03047872 0.87596268]

*** バイアス2 ***
[0.33619265 0.4758727  0.05144817 0.16308667]

##### 順伝播開始 #####
*** 総入力1 ***
[3.46953804 3.83987703 4.84481235 3.7066895  3.49916041]

*** 中間層出力1 ***
[3.46953804 3.83987703 4.84481235 3.7066895  3.49916041]

*** 総入力2 ***
[5.4164348  9.48487471 9.70985647 4.75483698]

*** 出力1 ***
[5.4164348  9.48487471 9.70985647 4.75483698]

出力合計: 19.36007734221611

##### 結果表示 #####
*** 中間層出力 ***
[3.46953804 3.83987703 4.84481235 3.7066895  3.49916041]

*** 出力 ***
[

# 2値分類（2-3-1ネットワーク）

In [53]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.random.rand(5,10)
    network['W2'] = np.random.rand(10,1)
    network['b1'] = np.array(10)
    network['b2'] = np.array(1)
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
x = np.array([1., 2., 2., 2., 2.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[16.66365147 13.16321025 13.85468089 13.50344454 12.72909966 12.82200417
 15.61350957 14.86223521 14.1815084  14.65887255]

*** 中間層出力1 ***
[16.66365147 13.16321025 13.85468089 13.50344454 12.72909966 12.82200417
 15.61350957 14.86223521 14.1815084  14.65887255]

*** 総入力2 ***
[76.20326786]

*** 出力1 ***
[1.]

出力合計: 142.05221669478573

##### 結果表示 #####
*** 中間層出力 ***
[16.66365147 13.16321025 13.85468089 13.50344454 12.72909966 12.82200417
 15.61350957 14.86223521 14.1815084  14.65887255]

*** 出力 ***
[1.]

*** 訓練データ ***
[1]

*** 誤差 ***
-9.999999505838704e-08

